repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-json

  - repo: https://gitlab.com/flywheel-io/flywheel-apps/utils/pre-commit-hooks
    rev: master
    hooks:
    - id: isort
    - id: black
    - id: pytest
    - id: validate-manifest

